name: Get Subscription Weekly

on:
  schedule:
    - cron: '0 0 */2 * *'  # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install tqdm
      run: |
        pip install tqdm

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py -s
      
    - name: Commit and push changes
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        if [ -n "$(git status --porcelain)" ]; then
          git add /home/runner/work/aggregator/aggregator/aggregate/data/proxies.yaml
          git add /home/runner/work/aggregator/aggregator/aggregate/data/subscribes.txt
          git add /home/runner/work/aggregator/aggregator/aggregate/data/domains.txt
          git add /home/runner/work/aggregator/aggregator/aggregate/data/valid-domains.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
